/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from sink_gatt_db.db_
 */

#include <panic.h>
#include <string.h>
#include "sink_gatt_db.h"

/* Static GATT database */
const uint16 gattDatabase[] = {
    /* 0001: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0002: Primary Service 180f */
    0x0002, 0x0f18,
    /* 0003: Characteristic Declaration 2a19 */
    0x3005, 0x1204, 0x0019, 0x2a00,
    /* 0004: . */
    0xd401, 0x0000,
    /* 0005: Client Characteristic Configuration */
    0x6c00,
    /* 0006: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0007: Characteristic Declaration 2a00 */
    0x3005, 0x0208, 0x0000, 0x2a00,
    /* 0008:  */
    0xd400,
    /* 0009: Characteristic Declaration 2a01 */
    0x3005, 0x020a, 0x0001, 0x2a00,
    /* 000a:  */
    0xd400,
};

uint16 *GattGetDatabase(uint16 *len)
{
    uint16 *rc = PanicUnlessMalloc(sizeof(gattDatabase));
    *len = sizeof(gattDatabase);
    memmove(rc, gattDatabase, sizeof(gattDatabase));
    return rc;
}

/* End-of-File */
