/****************************************************************************
Copyright (C) Cambridge Silicon Radio Limited 2012-2014
Part of ADK 3.5

FILE NAME
    sink_swat.h

DESCRIPTION
    Header file for interface with Subwoofer Audio Transfer library

NOTES

*/
#ifndef _SINK_SWAT_H_
#define _SINK_SWAT_H_

#ifdef ENABLE_SUBWOOFER

/* Application includes */
#include "sink_debug.h"
#include "sink_configmanager.h"
#include "sink_private.h"

/* Library includes */
#include <swat.h>
#include <bdaddr.h>
#include <connection.h>

/* SWAT Debug macro */
#ifdef DEBUG_SWAT
#define SWAT_DEBUG(x) DEBUG(x)
#else
#define SWAT_DEBUG(x)
#endif

/* Subwoofer COD = Service classes: Audio & Rendering, Major device class: Audio/Video Device, Minor Device class: Loudspeaker */
#define SUBWOOFER_CLASS_OF_DEVICE (AUDIO_MAJOR_SERV_CLASS | AV_COD_RENDER | AV_MAJOR_DEVICE_CLASS | AV_MINOR_SPEAKER) 

#define SW_MAX_REMOTE_DEVICES   1           /* The number of remote devices SWAT will support */
#define SW_MAX_INQUIRY_DEVS     5           /* The maximum number of subwoofer devices to return for inquiry mode */
#define SW_MAX_INQUIRY_TIME     10          /* The maximum time to enable inquiry mode when searching for subwoofer devices */
#define INQUIRY_LAP             0x9E8B33    /* The General/Unlimited Inquiry Access Code */
#define SW_INQUIRY_RETRY_TIME   11000       /* time after which another subwoofer inquiry is performed */
#define SW_INQUIRY_ATTEMPTS     3           /* number of times to try an inquiry scan */
#define SUB_WOOFER_CONNECT_RETRY_INTERVAL 30000 /* time before attempting another connection to the sub, allow other connections/pairing to complete */
#define SUB_TRIM_MAX            16          /* The maximum number of subwoofer trim volumes */
#define DEFAULT_SUB_TRIM_INDEX  10
#define SUBWOOFER_MUTE_DELAY    50          /* time required for subwoofer to reach mute state in milliseconds */
#define SUBWOOFER_LINK_SUPERVISION_TIMEOUT 1600 /* 1 second link supervision timeout */
/* 
    Defines the data structure for volume change messages
*/
typedef struct
{
    int16              new_volume;   /* subwoofer volume change level */
} SWAT_VOLUME_CHANGE_MSG_T;


/*
    Defines the data structure used for the Subwoofer configuration data
*/
typedef struct
{
    bdaddr              bd_addr;        /* Bluetooth address of the paired subwoofer device */
    sync_config_params  esco_params;    /* Custom eSCO SWAT parameters - if required */
} subwooferConfig_t;


/*************************************************************************
NAME    
    handleSwatMessage
    
DESCRIPTION
    Function to handle messages generated by the SWAT library
*/
void handleSwatMessage(Task task, MessageId id, Message message);


/*************************************************************************
NAME
    handleSubwooferGetAuthDevice
    
DESCRIPTION
    Handle CL_SM_GET_AUTH_DEVICE_CFM for subwoofer devices
*/
void handleSubwooferGetAuthDevice(CL_SM_GET_AUTH_DEVICE_CFM_T * cfm);


/*************************************************************************
NAME    
    handleEventUsrSubwooferStartInquiry
    
DESCRIPTION
    Function to handle the user event to start an inquiry search for
    a subwoofer device
*/
void handleEventUsrSubwooferStartInquiry(void);


/*************************************************************************
NAME    
    handleSubwooferInquiryResult
    
DESCRIPTION
    Function to handle when an Inquiry result is returned from CL when in 
    inquiry_action rssi_subwoofer.
*/
void handleSubwooferInquiryResult( CL_DM_INQUIRE_RESULT_T* result );


/*************************************************************************
NAME    
    handleEventSysSubwooferConnect
    
DESCRIPTION
    Function to handle the user event for connecting a subwoofer device
*/
void handleEventSysSubwooferCheckPairing(void);


/*************************************************************************
NAME    
    handleEventSysSubwooferOpenLLMedia
    
DESCRIPTION
    Function to handle the user event for opening a Low Latency SWAT 
    media channel to the subwoofer device
*/
void handleEventSysSubwooferOpenLLMedia(void);


/*************************************************************************
NAME    
    handleEventSysSubwooferOpenStdMedia
    
DESCRIPTION
    Function to handle the user event for opening a Standard Latency SWAT 
    media channel to the subwoofer device
*/
void handleEventSysSubwooferOpenStdMedia(void);


/*************************************************************************
NAME    
    handleEventSysSubwooferCloseMedia
    
DESCRIPTION
    Function to handle the user event for closing the open SWAT media
    channel to the subwoofer device
*/
void handleEventSysSubwooferCloseMedia(void);


/*************************************************************************
NAME    
    handleEventSysSubwooferStartStreaming
    
DESCRIPTION
    Function to handle the user event to start streaming audio data over
    the open SWAT media channel to the subwoofer device
*/
void handleEventSysSubwooferStartStreaming(void);


/*************************************************************************
NAME    
    handleEventSysSubwooferSuspendStreaming
    
DESCRIPTION
    Function to handle the user event to suspend audio streaming over the
    open SWAT media channel to the subwoofer device
*/
void handleEventSysSubwooferSuspendStreaming(void);


/*************************************************************************
NAME    
    handleEventSysSubwooferDisconnect
    
DESCRIPTION
    Function to handle the user event disconnect a connected subwoofer
    device
*/
void handleEventSysSubwooferDisconnect(void);


/*************************************************************************
NAME    
    handleEventUsrSubwooferVolumeDown
    
DESCRIPTION
    Function to handle the user event to decrease the subwoofer volume
*/
void handleEventUsrSubwooferVolumeDown(void);


/*************************************************************************
NAME    
    handleEventUsrSubwooferVolumeUp
    
DESCRIPTION
    Function to handle the user event to decrease the subwoofer volume
*/
void handleEventUsrSubwooferVolumeUp(void);


/*************************************************************************
NAME    
    handleEventUsrSubwooferDeletePairing
    
DESCRIPTION
    Function to handle the user event to delete the subwoofer pairing info
    from the soundbar PDL
*/
void handleEventUsrSubwooferDeletePairing(void);


/*************************************************************************
NAME    
    updateSwatVolume
    
DESCRIPTION
    Function to update the SWAT system volume that is also sent to the 
    subwoofer device to keep volume sync'd
*/
void updateSwatVolume(int16 new_volume);
void updateSwatVolumeNow(int16 new_volume);


/*************************************************************************
NAME    
    deleteSubwooferPairing

PARAMETERS
    delete_link_key - Flag to also delete the link key, otherwise will
    only delete the PS Data from CONFIG_SUBWOOFER.

DESCRIPTION
    Function to delete the subwoofer pairing informtion from the soundbar
*/
void deleteSubwooferPairing(bool delete_link_key);


/*************************************************************************
NAME    
    sendSampleRateToSub
    
DESCRIPTION
    Function to send the sample rate (in use) to the subwoofer
*/
void sendSampleRateToSub(uint16 sample_rate);

/*************************************************************************
NAME    
    sendMuteToSubwoofer
    
DESCRIPTION
    Function to set the subwoofer to mute state to reduce pops when changing sources
*/
void sendMuteToSubwoofer(void);

#endif /* ENABLE_SUBWOOFER */


#endif /* _SINK_SWAT_H_ */
