/*
    Warning - this file was autogenerated by genparse
    DO NOT EDIT - any changes will be lost
*/

#include "hfp_parse.h"

#include <ctype.h>
#include <panic.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <util.h> /* hash and compare */

#if (defined TEST_HARNESS || defined DISPLAY_AT_CMDS)
#include <stdio.h>
#endif

typedef const uint8 *ptr;

static __inline__ char my_toupper(char c)
{ return 'a' <= c && c <= 'z' ? c +'A'-'a' : c; }

static ptr skip1(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == ' ' || *s == '\t'))
      ++s;
  return s;
}

static ptr skipOnce1(ptr s, ptr e)
{
  if(s)
  {
    if(s != e && (*s == ',' || *s == ';'))
      ++s;
  }
  return s;
}

#ifdef TEST_HARNESS
static void printString(const char *name, const struct sequence *s)
{
  uint16 i;
  printf(" %s='", name);
  for(i = 0; i < s->length; ++i) putchar(s->data[i]);
  printf("'");
}
#endif

static __inline__ ptr skipQuote(ptr p, ptr e)
{ return p && p != e && *p == '"' ? p+1 : p; }

static const int isStringTable[] =
{
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,0,0,1,0,0,0,0,0,0,1,1,0,1,0,1,
    1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0
};

static __inline__ int isString(char c)
{
    return (c & ~0x7F) == 0 && isStringTable[(int)c];
}

static ptr getString(ptr p, ptr e, struct sequence *res)
{
  p = skipQuote(p, e);
  if(p)
  {
    ptr s = p;
    while(p != e && isString(*p)) ++p;
    if(p != s)
    {
        res->data = s;
        res->length = p - s;
        return skipQuote(p, e);
    }
    else
    {
        p = skipQuote(p, e);
        if (*p==',' || *p == '\r')
        {
            res->data = 0;
            res->length = 0;
            return p;
        }
    }
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr getWildString(ptr p, ptr e, struct sequence *res)
{
  if(p)
  {
    ptr s = p;
    p = (uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16) (e - p));
    if (!p) p = (uint8*)UtilFind(0xFFFF, '\n', (const uint16*)p, 0, 1, e - p);
    if (!p) p = e;
    res->data = s;
    res->length = p - s;
    return p;
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr match1(ptr s, ptr e)
{ return s && s != e && (*s == '\r' || *s == '\n') ? s+1 : 0; }

static ptr skip2(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == '(' || *s == ')'))
      ++s;
  return s;
}

struct value_hfpCsrFeaturesHandleModifyIndicatorsInd_p get_hfpCsrFeaturesHandleModifyIndicatorsInd_p(const struct region_hfpCsrFeaturesHandleModifyIndicatorsInd_p *r0, uint16 i)
{
  struct region_hfpCsrFeaturesHandleModifyIndicatorsInd_p * r = (struct region_hfpCsrFeaturesHandleModifyIndicatorsInd_p *) r0;
  if(i < r->next)
  {
    r->next   = 0;
    r->next_s = r->s;
  }
  {
    uint16 n = r->next;
    ptr p = r->next_s;
    ptr e = r->e;
    struct value_hfpCsrFeaturesHandleModifyIndicatorsInd_p res;
    while(p && p != e && n <= i)
    {
      ++n;
      p = skip1(skipOnce1(skip1(skip1(skip2(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skip2(skip1(p, e), e), e), e, &res.ind), e), e), e), e, &res.val), e), e), e), e), e), e);
    }
    r->next   = n;
    r->next_s = p;
    return res;
  }
}

static ptr loop4(ptr p, ptr e, struct region_hfpCsrFeaturesHandleModifyIndicatorsInd_p *res)
{
  int n = 0;
  struct value_hfpCsrFeaturesHandleModifyIndicatorsInd_p dummy;
  res->s = p;
  while(p && p != e && n < 99)
  {
    ptr pp = skip1(skip2(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skip2(skip1(p, e), e), e), e, &dummy.ind), e), e), e), e, &dummy.val), e), e), e);
    if(!pp) break; else p = pp;
    if(++n < 99)
      p = skip1(skipOnce1(skip1(p, e), e), e);
  }
  res->e      = p;
  res->count  = n;
  res->next   = 0;
  res->next_s = res->s;
  return 1 <= n ? p : 0;
}

static ptr matchChar(ptr s, ptr e, uint8 c)
{ return s && s != e && my_toupper((char) *s) == (char) c ? s+1 : 0; }

static ptr skip3(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == '-'))
      ++s;
  return s;
}

struct value_hfpHandleCallHoldInfoRange_p get_hfpHandleCallHoldInfoRange_p(const struct region_hfpHandleCallHoldInfoRange_p *r0, uint16 i)
{
  struct region_hfpHandleCallHoldInfoRange_p * r = (struct region_hfpHandleCallHoldInfoRange_p *) r0;
  if(i < r->next)
  {
    r->next   = 0;
    r->next_s = r->s;
  }
  {
    uint16 n = r->next;
    ptr p = r->next_s;
    ptr e = r->e;
    struct value_hfpHandleCallHoldInfoRange_p res;
    while(p && p != e && n <= i)
    {
      ++n;
      p = skip1(skipOnce1(skip1(UtilGetNumber(skip1(skip3(skip1(UtilGetNumber(p, e, &res.lower), e), e), e), e, &res.upper), e), e), e);
    }
    r->next   = n;
    r->next_s = p;
    return res;
  }
}

static ptr loop2(ptr p, ptr e, struct region_hfpHandleCallHoldInfoRange_p *res)
{
  int n = 0;
  struct value_hfpHandleCallHoldInfoRange_p dummy;
  res->s = p;
  while(p && p != e && n < 99)
  {
    ptr pp = UtilGetNumber(skip1(skip3(skip1(UtilGetNumber(p, e, &dummy.lower), e), e), e), e, &dummy.upper);
    if(!pp) break; else p = pp;
    if(++n < 99)
      p = skip1(skipOnce1(skip1(p, e), e), e);
  }
  res->e      = p;
  res->count  = n;
  res->next   = 0;
  res->next_s = res->s;
  return 1 <= n ? p : 0;
}

struct value_hfpHandleCallHoldInfo_p get_hfpHandleCallHoldInfo_p(const struct region_hfpHandleCallHoldInfo_p *r0, uint16 i)
{
  struct region_hfpHandleCallHoldInfo_p * r = (struct region_hfpHandleCallHoldInfo_p *) r0;
  if(i < r->next)
  {
    r->next   = 0;
    r->next_s = r->s;
  }
  {
    uint16 n = r->next;
    ptr p = r->next_s;
    ptr e = r->e;
    struct value_hfpHandleCallHoldInfo_p res;
    while(p && p != e && n <= i)
    {
      ++n;
      p = skip1(skipOnce1(skip1(getString(p, e, &res.n), e), e), e);
    }
    r->next   = n;
    r->next_s = p;
    return res;
  }
}

static ptr loop3(ptr p, ptr e, struct region_hfpHandleCallHoldInfo_p *res)
{
  int n = 0;
  struct value_hfpHandleCallHoldInfo_p dummy;
  res->s = p;
  while(p && p != e && n < 99)
  {
    ptr pp = getString(p, e, &dummy.n);
    if(!pp) break; else p = pp;
    if(++n < 99)
      p = skip1(skipOnce1(skip1(p, e), e), e);
  }
  res->e      = p;
  res->count  = n;
  res->next   = 0;
  res->next_s = res->s;
  return 1 <= n ? p : 0;
}

struct value_hfpHandleIndicatorStatus_d get_hfpHandleIndicatorStatus_d(const struct region_hfpHandleIndicatorStatus_d *r0, uint16 i)
{
  struct region_hfpHandleIndicatorStatus_d * r = (struct region_hfpHandleIndicatorStatus_d *) r0;
  if(i < r->next)
  {
    r->next   = 0;
    r->next_s = r->s;
  }
  {
    uint16 n = r->next;
    ptr p = r->next_s;
    ptr e = r->e;
    struct value_hfpHandleIndicatorStatus_d res;
    while(p && p != e && n <= i)
    {
      ++n;
      p = skip1(skipOnce1(skip1(UtilGetNumber(p, e, &res.n), e), e), e);
    }
    r->next   = n;
    r->next_s = p;
    return res;
  }
}

static ptr loop1(ptr p, ptr e, struct region_hfpHandleIndicatorStatus_d *res)
{
  int n = 0;
  struct value_hfpHandleIndicatorStatus_d dummy;
  res->s = p;
  while(p && p != e && n < 99)
  {
    ptr pp = UtilGetNumber(p, e, &dummy.n);
    if(!pp) break; else p = pp;
    if(++n < 99)
      p = skip1(skipOnce1(skip1(p, e), e), e);
  }
  res->e      = p;
  res->count  = n;
  res->next   = 0;
  res->next_s = res->s;
  return 2 <= n ? p : 0;
}

static ptr findEndOfPacket(ptr s, ptr e)
{
  /*
     Returns
     0   if the buffer holds an incomplete packet
     s+1 if the buffer holds an invalid packet
     end of the first packet otherwise
  */
  if(s == e) return 0;

  if(*s == '\r')
  {
    /* expecting <cr> <lf> ... <cr> <lf> */
    if(e-s >= 4)
    {
      if(s[1] == '\n' && s[2] != '\r')
      {
        ptr p = s+2;
        if(*p != '\r')
        {
#ifndef TEST_HARNESS
        p = (const uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16)(e-p));
#endif
#ifdef TEST_HARNESS
		   while(p != e && *p != '\r') p++;
#endif
        return p == 0 || p + 1 == e ? 0 /* no terminator yet */
             : p[1] == '\n' ? p+2 /* valid */
             : s+1 ; /* invalid terminator */
         }
         else
             return s+1;
      }
      else
      {
        return s+1;
      }
    }
    else
    {
      /* Can't tell yet */
      return 0;
    }
  }
  else
  {
    /* expecting ... <cr> */
    ptr p = s;
    while(p != e && (*p == ' ' || *p == '\0' || *p == '\t')) ++p;
    if(p != e && (*p == '\r' || *p == '\n' )) return s+1;
    while(p != e && *p != '\r') ++p;
    return p == e ? 0 : p+1;
  }
}

#ifndef TEST_HARNESS
#ifdef __XAP__
uint16 parseSource(Source rfcDataIn, Task task)
{
  ptr s = SourceMap(rfcDataIn);
  ptr e = s + SourceSize(rfcDataIn);
  ptr p = parseData(s, e, task);
  if(p != s)
  {
    SourceDrop(rfcDataIn, (uint16) (p - s));
    return 1;
  }
  else
  {
    return 0;
  }
}
#endif
#endif

typedef struct {
  char c;
  int to;
} Arc;

static const Arc arcs[] = {
  { '\t', 0 },
  { '\n', 1 },
  { '\r', 1 },
  { ' ', 0 },
  { '+', 2 },
  { '\t', 1 },
  { '\n', 3 },
  { '\r', 3 },
  { ' ', 1 },
  { '\t', 2 },
  { ' ', 2 },
  { 'C', 4 },
  { '\t', 3 },
  { ' ', 3 },
  { '+', 5 },
  { 'E', 6 },
  { 'N', 7 },
  { 'O', 8 },
  { 'R', 9 },
  { 'L', 10 },
  { '\t', 11 },
  { ' ', 11 },
  { 'B', 12 },
  { 'C', 13 },
  { 'M', 14 },
  { 'V', 15 },
  { 'R', 16 },
  { 'O', 17 },
  { 'K', 18 },
  { 'I', 19 },
  { 'C', 20 },
  { '\t', 11 },
  { ' ', 11 },
  { 'B', 12 },
  { 'C', 13 },
  { 'V', 15 },
  { 'C', 21 },
  { 'I', 22 },
  { 'R', 23 },
  { 'S', 24 },
  { 'T', 25 },
  { 'V', 26 },
  { 'C', 27 },
  { 'H', 28 },
  { 'I', 29 },
  { 'L', 30 },
  { 'M', 31 },
  { 'N', 32 },
  { 'O', 33 },
  { 'S', 34 },
  { 'B', 35 },
  { 'G', 36 },
  { 'R', 37 },
  { '\t', 17 },
  { ' ', 17 },
  { 'C', 38 },
  { '\t', 18 },
  { '\n', 39 },
  { '\r', 39 },
  { ' ', 18 },
  { 'N', 40 },
  { 'C', 41 },
  { 'S', 42 },
  { 'N', 43 },
  { 'S', 44 },
  { 'I', 45 },
  { 'R', 46 },
  { 'R', 47 },
  { 'W', 48 },
  { 'L', 49 },
  { 'E', 50 },
  { 'N', 51 },
  { 'C', 20 },
  { 'I', 52 },
  { 'E', 53 },
  { 'U', 54 },
  { 'P', 55 },
  { 'R', 56 },
  { 'A', 57 },
  { 'M', 58 },
  { 'S', 59 },
  { 'O', 60 },
  { 'A', 61 },
  { '\t', 39 },
  { '\n', -1 },
  { '\r', -1 },
  { ' ', 39 },
  { 'G', 62 },
  { '\t', 41 },
  { ' ', 41 },
  { ':', -2 },
  { '=', -2 },
  { '\t', 42 },
  { ' ', 42 },
  { ':', -3 },
  { '=', -3 },
  { 'P', 63 },
  { 'F', 64 },
  { 'R', 65 },
  { 'H', 66 },
  { 'A', 67 },
  { 'A', 68 },
  { 'D', 69 },
  { 'V', 70 },
  { 'D', 71 },
  { 'P', 72 },
  { '\t', 53 },
  { ' ', 53 },
  { 'E', 73 },
  { 'M', 74 },
  { 'S', 75 },
  { '\t', 76 },
  { ' ', 76 },
  { ':', -4 },
  { '=', -4 },
  { 'B', 77 },
  { 'G', 78 },
  { 'S', 79 },
  { 'T', 80 },
  { 'N', 81 },
  { '\t', 58 },
  { ' ', 58 },
  { ':', -5 },
  { '=', -5 },
  { '\t', 59 },
  { ' ', 59 },
  { ':', -6 },
  { '=', -6 },
  { 'R', 82 },
  { 'R', 83 },
  { '\t', 62 },
  { '\n', 84 },
  { '\r', 84 },
  { ' ', 62 },
  { '\t', 63 },
  { ' ', 63 },
  { ':', -7 },
  { '=', -7 },
  { '\t', 64 },
  { ' ', 64 },
  { ':', -8 },
  { '=', -8 },
  { '\t', 65 },
  { ' ', 65 },
  { ':', -9 },
  { '=', -9 },
  { '\t', 66 },
  { ' ', 66 },
  { ':', -10 },
  { '=', -10 },
  { '\t', 67 },
  { ' ', 67 },
  { ':', -11 },
  { '=', -11 },
  { '\t', 68 },
  { ' ', 68 },
  { ':', -12 },
  { '=', -12 },
  { '\t', 69 },
  { ' ', 69 },
  { ':', -13 },
  { '=', -13 },
  { '\t', 70 },
  { ' ', 70 },
  { ':', -14 },
  { '=', -14 },
  { '\t', 71 },
  { ' ', 71 },
  { ':', -15 },
  { '=', -15 },
  { '\t', 72 },
  { ' ', 72 },
  { ':', -16 },
  { '=', -16 },
  { 'R', 85 },
  { '\t', 74 },
  { ' ', 74 },
  { ':', -17 },
  { '=', -17 },
  { '\t', 75 },
  { ' ', 75 },
  { ':', -18 },
  { '=', -18 },
  { '\t', 76 },
  { ' ', 76 },
  { ':', -4 },
  { '=', -4 },
  { 'A', 86 },
  { 'E', 87 },
  { 'F', 88 },
  { 'M', 89 },
  { 'X', 90 },
  { ':', -19 },
  { '=', -19 },
  { '\t', 82 },
  { '\n', 91 },
  { '\r', 91 },
  { ' ', 82 },
  { 'R', 92 },
  { '\t', 84 },
  { '\n', -20 },
  { '\r', -20 },
  { ' ', 84 },
  { 'R', 93 },
  { 'T', 94 },
  { 'T', 95 },
  { '\t', 88 },
  { ' ', 88 },
  { ':', -21 },
  { '=', -21 },
  { 'S', 96 },
  { 'T', 97 },
  { '\t', 91 },
  { '\n', -22 },
  { '\r', -22 },
  { ' ', 91 },
  { 'I', 98 },
  { 'O', 99 },
  { 'T', 100 },
  { 'S', 101 },
  { '\t', 96 },
  { ' ', 96 },
  { ':', -23 },
  { '=', -23 },
  { '\t', 97 },
  { ' ', 97 },
  { ':', -24 },
  { '=', -24 },
  { 'E', 102 },
  { 'R', 103 },
  { '\t', 104 },
  { '\n', 105 },
  { '\r', 105 },
  { ' ', 104 },
  { '?', 100 },
  { 'M', 106 },
  { 'R', 107 },
  { '\t', 103 },
  { ' ', 103 },
  { ':', -25 },
  { '=', -25 },
  { '\t', 104 },
  { '\n', 105 },
  { '\r', 105 },
  { ' ', 104 },
  { '\t', 105 },
  { '\n', -26 },
  { '\r', -26 },
  { ' ', 105 },
  { 'S', 108 },
  { '\t', 107 },
  { '\n', 109 },
  { '\r', 109 },
  { ' ', 107 },
  { '\t', 108 },
  { ' ', 108 },
  { ':', -27 },
  { '=', -27 },
  { '\t', 109 },
  { '\n', -28 },
  { '\r', -28 },
  { ' ', 109 },
};

static const Arc *const states[111] = {
  &arcs[0],
  &arcs[5],
  &arcs[9],
  &arcs[12],
  &arcs[19],
  &arcs[20],
  &arcs[26],
  &arcs[27],
  &arcs[28],
  &arcs[29],
  &arcs[30],
  &arcs[31],
  &arcs[36],
  &arcs[42],
  &arcs[50],
  &arcs[51],
  &arcs[52],
  &arcs[53],
  &arcs[56],
  &arcs[60],
  &arcs[61],
  &arcs[62],
  &arcs[63],
  &arcs[64],
  &arcs[65],
  &arcs[66],
  &arcs[67],
  &arcs[68],
  &arcs[69],
  &arcs[70],
  &arcs[72],
  &arcs[74],
  &arcs[75],
  &arcs[76],
  &arcs[77],
  &arcs[78],
  &arcs[79],
  &arcs[81],
  &arcs[82],
  &arcs[83],
  &arcs[87],
  &arcs[88],
  &arcs[92],
  &arcs[96],
  &arcs[97],
  &arcs[98],
  &arcs[99],
  &arcs[100],
  &arcs[101],
  &arcs[102],
  &arcs[103],
  &arcs[104],
  &arcs[105],
  &arcs[106],
  &arcs[109],
  &arcs[110],
  &arcs[111],
  &arcs[119],
  &arcs[120],
  &arcs[124],
  &arcs[128],
  &arcs[129],
  &arcs[130],
  &arcs[134],
  &arcs[138],
  &arcs[142],
  &arcs[146],
  &arcs[150],
  &arcs[154],
  &arcs[158],
  &arcs[162],
  &arcs[166],
  &arcs[170],
  &arcs[174],
  &arcs[175],
  &arcs[179],
  &arcs[183],
  &arcs[187],
  &arcs[188],
  &arcs[189],
  &arcs[191],
  &arcs[192],
  &arcs[194],
  &arcs[198],
  &arcs[199],
  &arcs[203],
  &arcs[204],
  &arcs[205],
  &arcs[206],
  &arcs[210],
  &arcs[211],
  &arcs[212],
  &arcs[216],
  &arcs[217],
  &arcs[218],
  &arcs[219],
  &arcs[220],
  &arcs[224],
  &arcs[228],
  &arcs[229],
  &arcs[230],
  &arcs[235],
  &arcs[236],
  &arcs[237],
  &arcs[241],
  &arcs[245],
  &arcs[249],
  &arcs[250],
  &arcs[254],
  &arcs[258],
  &arcs[262],
};

static uint16 matchLiteral(ptr s, ptr e, Task task)
{
  uint16 n = e - s;
  uint16 h = 0;
  uint16 i = 0;
  do {
    uint16 m = n - i;
    if(m > 64)
      m = 64;
    h = UtilHash((uint16 *) s + i, m, h);
    i += m;
  } while(i < n);
  switch(h)
  {
    case 3689:
      {
        const char *literal = "\r\n+BSIR: 0\r\n";
        if(n == 12 && UtilCompare((uint16 *)(literal+0), (uint16 *)(s+0), 12) == 0)
        {
#ifndef TEST_HARNESS
          hfpHandleInBandRingToneDisable(task);
#endif
#ifdef TEST_HARNESS
          printf("Called hfpHandleInBandRingToneDisable\n");
#endif
          return 1;
        }
      }
      break;
    case 8704:
      {
        const char *literal = "\r\n+CHLD: (0,1,1x,2,2x,3,4)\r\n";
        if(n == 28 && UtilCompare((uint16 *)(literal+0), (uint16 *)(s+0), 28) == 0)
        {
#ifndef TEST_HARNESS
          hfpHandleCallHoldInfoCommon(task);
#endif
#ifdef TEST_HARNESS
          printf("Called hfpHandleCallHoldInfoCommon\n");
#endif
          return 1;
        }
      }
      break;
    case 14274:
      {
        const char *literal = "\r\nOK\r\n";
        if(n == 6 && UtilCompare((uint16 *)(literal+0), (uint16 *)(s+0), 6) == 0)
        {
#ifndef TEST_HARNESS
          hfpHandleOk(task);
#endif
#ifdef TEST_HARNESS
          printf("Called hfpHandleOk\n");
#endif
          return 1;
        }
      }
      break;
    case 25656:
      {
        const char *literal = "\r\nERROR\r\n";
        if(n == 9 && UtilCompare((uint16 *)(literal+0), (uint16 *)(s+0), 9) == 0)
        {
#ifndef TEST_HARNESS
          hfpHandleError(task);
#endif
#ifdef TEST_HARNESS
          printf("Called hfpHandleError\n");
#endif
          return 1;
        }
      }
      break;
    case 31798:
      {
        const char *literal = "\r\nRING\r\n";
        if(n == 8 && UtilCompare((uint16 *)(literal+0), (uint16 *)(s+0), 8) == 0)
        {
#ifndef TEST_HARNESS
          hfpHandleRing(task);
#endif
#ifdef TEST_HARNESS
          printf("Called hfpHandleRing\n");
#endif
          return 1;
        }
      }
      break;
    case 37456:
      {
        const char *literal = "\r\n+BSIR: 1\r\n";
        if(n == 12 && UtilCompare((uint16 *)(literal+0), (uint16 *)(s+0), 12) == 0)
        {
#ifndef TEST_HARNESS
          hfpHandleInBandRingToneEnable(task);
#endif
#ifdef TEST_HARNESS
          printf("Called hfpHandleInBandRingToneEnable\n");
#endif
          return 1;
        }
      }
      break;
  }
  return 0;
}

ptr parseData(ptr s, ptr e, Task task)
{
  ptr p;

#ifdef DISPLAY_AT_CMDS
  {
  	ptr c = s;
    printf("\nreceived: ");
  	while (c != e)
  	{
		if (*c == '\r')			printf("\\r");
		else if (*c == '\n') 	printf("\\n");
		else 					putchar(*c);

		c++;
  	}
  }
#endif

#ifdef TEST_HARNESS
  task = task;
#endif
  for(; (p = findEndOfPacket(s, e)) != 0; s = p)
  {
    if(p == s+1)
    {
      /* Silently discard one character; no packets are that short */
      continue;
    }
    else if(matchLiteral(s, p, task))
    {
      continue;
    }
    else
    {
      union {
        struct hfpHandleCurrentCallsWithNumber hfpHandleCurrentCallsWithNumber;
        struct hfpHandleCurrentCalls hfpHandleCurrentCalls;
        struct hfpHandleResponseWbsCodec hfpHandleResponseWbsCodec;
        struct hfpCsrFeaturesHandleModifyIndicatorsInd hfpCsrFeaturesHandleModifyIndicatorsInd;
        struct hfpHandleMicrophoneGain hfpHandleMicrophoneGain;
        struct hfpHandleSpeakerGain hfpHandleSpeakerGain;
        struct hfpHandleDataResponse hfpHandleDataResponse;
        struct hfpHandleDataResponseExtended hfpHandleDataResponseExtended;
        struct hfpHandleSupportedFeaturesInd hfpHandleSupportedFeaturesInd;
        struct hfpHandleInBandRingTone hfpHandleInBandRingTone;
        struct hfpHandleResponseHold hfpHandleResponseHold;
        struct hfpHandleVoiceRecognitionStatus hfpHandleVoiceRecognitionStatus;
        struct hfpHandleCallWaitingNotificationWithName hfpHandleCallWaitingNotificationWithName;
        struct hfpHandleCallWaitingNotification hfpHandleCallWaitingNotification;
        struct hfpHandleCallWaitingNotificationIllegal hfpHandleCallWaitingNotificationIllegal;
        struct hfpHandleCallHoldInfoRange hfpHandleCallHoldInfoRange;
        struct hfpHandleCallHoldInfo hfpHandleCallHoldInfo;
        struct hfpHandleIndicatorStatusUpdate hfpHandleIndicatorStatusUpdate;
        struct hfpHandleIndicatorStatus hfpHandleIndicatorStatus;
        struct hfpHandleIndicatorList hfpHandleIndicatorList;
        struct hfpHandleCallerIdWithName hfpHandleCallerIdWithName;
        struct hfpHandleCallerId hfpHandleCallerId;
        struct hfpHandleCallerIdIllegal hfpHandleCallerIdIllegal;
        struct hfpHandleSubscriberNumber hfpHandleSubscriberNumber;
        struct hfpHandleNetworkOperatorModeName hfpHandleNetworkOperatorModeName;
        struct hfpHandleNetworkOperatorMode hfpHandleNetworkOperatorMode;
        struct hfpHandleNull hfpHandleNull;
        struct hfpCsrFeaturesHandleBandwidthCodecRes hfpCsrFeaturesHandleBandwidthCodecRes;
        struct hfpCsrFeaturesHandleCodecRes hfpCsrFeaturesHandleCodecRes;
        struct hfpCsrFeaturesHandleNormalRes hfpCsrFeaturesHandleNormalRes;
        struct hfpCsrFeaturesHandleSmsInd hfpCsrFeaturesHandleSmsInd;
        struct hfpCsrFeaturesHandleTextInd hfpCsrFeaturesHandleTextInd;
        struct hfpHandleExtendedError hfpHandleExtendedError;
        struct hfpCsrFeaturesHandleGetSmsRes hfpCsrFeaturesHandleGetSmsRes;
      } u, *uu = &u;
      int state = 0;
      ptr t = s;
      while(t != e && state >= 0)
      {
        char m = my_toupper((char) *t);
        const Arc *a = states[state];
        const Arc *const last_a = states[state+1];
#ifndef TEST_HARNESS
        a = (const Arc *) (void *) UtilFind(0xFFFF, (uint16) m, (const uint16 *) (void *) &a[0].c, 0, sizeof(Arc), (uint16) (last_a - a));
#endif
#ifdef TEST_HARNESS
        while(a != last_a && a->c != m) a++;
#endif
        /*lint -e{801} suppress goto is deprecated */
        if(!a) goto unrecognised;
        state = a->to;
        ++t;
      }
      switch(-state)
      {
        case 1:
          if(t)
          {
#ifndef TEST_HARNESS
            hfpHandleOk(task);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleOk");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 2:
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleCurrentCallsWithNumber.idx), e), e), e), e, &uu->hfpHandleCurrentCallsWithNumber.dir), e), e), e), e, &uu->hfpHandleCurrentCallsWithNumber.status), e), e), e), e, &uu->hfpHandleCurrentCallsWithNumber.mode), e), e), e), e, &uu->hfpHandleCurrentCallsWithNumber.mprty), e), e), e), e, &uu->hfpHandleCurrentCallsWithNumber.number), e), e), e), e, &uu->hfpHandleCurrentCallsWithNumber.type), e), e), e), e, &uu->hfpHandleCurrentCallsWithNumber.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCurrentCallsWithNumber(task, &uu->hfpHandleCurrentCallsWithNumber);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCurrentCallsWithNumber");
            printf(" idx=%d", uu->hfpHandleCurrentCallsWithNumber.idx);
            printf(" dir=%d", uu->hfpHandleCurrentCallsWithNumber.dir);
            printf(" status=%d", uu->hfpHandleCurrentCallsWithNumber.status);
            printf(" mode=%d", uu->hfpHandleCurrentCallsWithNumber.mode);
            printf(" mprty=%d", uu->hfpHandleCurrentCallsWithNumber.mprty);
            printString("number", &uu->hfpHandleCurrentCallsWithNumber.number);
            printf(" type=%d", uu->hfpHandleCurrentCallsWithNumber.type);
            printString("ignore", &uu->hfpHandleCurrentCallsWithNumber.ignore);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleCurrentCalls.idx), e), e), e), e, &uu->hfpHandleCurrentCalls.dir), e), e), e), e, &uu->hfpHandleCurrentCalls.status), e), e), e), e, &uu->hfpHandleCurrentCalls.mode), e), e), e), e, &uu->hfpHandleCurrentCalls.mprty), e), e), e), e, &uu->hfpHandleCurrentCalls.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCurrentCalls(task, &uu->hfpHandleCurrentCalls);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCurrentCalls");
            printf(" idx=%d", uu->hfpHandleCurrentCalls.idx);
            printf(" dir=%d", uu->hfpHandleCurrentCalls.dir);
            printf(" status=%d", uu->hfpHandleCurrentCalls.status);
            printf(" mode=%d", uu->hfpHandleCurrentCalls.mode);
            printf(" mprty=%d", uu->hfpHandleCurrentCalls.mprty);
            printString("ignore", &uu->hfpHandleCurrentCalls.ignore);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 3:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleResponseWbsCodec.codec), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleResponseWbsCodec(task, &uu->hfpHandleResponseWbsCodec);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleResponseWbsCodec");
            printf(" codec=%d", uu->hfpHandleResponseWbsCodec.codec);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 4:
          if(match1(skip1(match1(skip1(loop4(skip1(t, e), e, &uu->hfpCsrFeaturesHandleModifyIndicatorsInd.p), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleModifyIndicatorsInd(task, &uu->hfpCsrFeaturesHandleModifyIndicatorsInd);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleModifyIndicatorsInd");
            {
              uint16 i;
              struct region_hfpCsrFeaturesHandleModifyIndicatorsInd_p *r = &uu->hfpCsrFeaturesHandleModifyIndicatorsInd.p;
              printf(" p={");
              for(i = 0; i < r->count; ++i)
              {
                struct value_hfpCsrFeaturesHandleModifyIndicatorsInd_p t = get_hfpCsrFeaturesHandleModifyIndicatorsInd_p(r, i);
                putchar('{');
                printf(" ind=%d", t.ind);
                printf(" val=%d", t.val);
                putchar('}');
              }
              putchar('}');
            }
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(matchChar(skip1(t, e), e, '0'), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleDisableIndicatorsInd(task);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleDisableIndicatorsInd");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 5:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleMicrophoneGain.gain), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleMicrophoneGain(task, &uu->hfpHandleMicrophoneGain);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleMicrophoneGain");
            printf(" gain=%d", uu->hfpHandleMicrophoneGain.gain);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 6:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleSpeakerGain.gain), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleSpeakerGain(task, &uu->hfpHandleSpeakerGain);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleSpeakerGain");
            printf(" gain=%d", uu->hfpHandleSpeakerGain.gain);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 7:
          if(match1(skip1(match1(skip1(getString(skip1(t, e), e, &uu->hfpHandleDataResponse.num), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleDataResponse(task, &uu->hfpHandleDataResponse);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleDataResponse");
            printString("num", &uu->hfpHandleDataResponse.num);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->hfpHandleDataResponseExtended.num), e), e), e), e, &uu->hfpHandleDataResponseExtended.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleDataResponseExtended(task, &uu->hfpHandleDataResponseExtended);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleDataResponseExtended");
            printString("num", &uu->hfpHandleDataResponseExtended.num);
            printString("ignore", &uu->hfpHandleDataResponseExtended.ignore);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 8:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleSupportedFeaturesInd.supportedfeat), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleSupportedFeaturesInd(task, &uu->hfpHandleSupportedFeaturesInd);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleSupportedFeaturesInd");
            printf(" supportedfeat=%d", uu->hfpHandleSupportedFeaturesInd.supportedfeat);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 9:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleInBandRingTone.enable), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleInBandRingTone(task, &uu->hfpHandleInBandRingTone);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleInBandRingTone");
            printf(" enable=%d", uu->hfpHandleInBandRingTone.enable);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 10:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleResponseHold.state), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleResponseHold(task, &uu->hfpHandleResponseHold);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleResponseHold");
            printf(" state=%d", uu->hfpHandleResponseHold.state);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 11:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleVoiceRecognitionStatus.enable), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleVoiceRecognitionStatus(task, &uu->hfpHandleVoiceRecognitionStatus);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleVoiceRecognitionStatus");
            printf(" enable=%d", uu->hfpHandleVoiceRecognitionStatus.enable);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 12:
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->hfpHandleCallWaitingNotificationWithName.num), e), e), e), e, &uu->hfpHandleCallWaitingNotificationWithName.type), e), e), e), e, &uu->hfpHandleCallWaitingNotificationWithName.class), e), e), e), e, &uu->hfpHandleCallWaitingNotificationWithName.name), e), e), e), e, &uu->hfpHandleCallWaitingNotificationWithName.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCallWaitingNotificationWithName(task, &uu->hfpHandleCallWaitingNotificationWithName);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCallWaitingNotificationWithName");
            printString("num", &uu->hfpHandleCallWaitingNotificationWithName.num);
            printf(" type=%d", uu->hfpHandleCallWaitingNotificationWithName.type);
            printf(" class=%d", uu->hfpHandleCallWaitingNotificationWithName.class);
            printString("name", &uu->hfpHandleCallWaitingNotificationWithName.name);
            printString("ignore", &uu->hfpHandleCallWaitingNotificationWithName.ignore);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->hfpHandleCallWaitingNotification.num), e), e), e), e, &uu->hfpHandleCallWaitingNotification.type), e), e), e), e, &uu->hfpHandleCallWaitingNotification.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCallWaitingNotification(task, &uu->hfpHandleCallWaitingNotification);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCallWaitingNotification");
            printString("num", &uu->hfpHandleCallWaitingNotification.num);
            printf(" type=%d", uu->hfpHandleCallWaitingNotification.type);
            printString("ignore", &uu->hfpHandleCallWaitingNotification.ignore);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->hfpHandleCallWaitingNotificationIllegal.num), e), e), e), e, &uu->hfpHandleCallWaitingNotificationIllegal.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCallWaitingNotificationIllegal(task, &uu->hfpHandleCallWaitingNotificationIllegal);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCallWaitingNotificationIllegal");
            printString("num", &uu->hfpHandleCallWaitingNotificationIllegal.num);
            printString("ignore", &uu->hfpHandleCallWaitingNotificationIllegal.ignore);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 13:
          if(match1(skip1(match1(skip1(skip2(skip1(loop2(skip1(skip2(skip1(t, e), e), e), e, &uu->hfpHandleCallHoldInfoRange.p), e), e), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCallHoldInfoRange(task, &uu->hfpHandleCallHoldInfoRange);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCallHoldInfoRange");
            {
              uint16 i;
              struct region_hfpHandleCallHoldInfoRange_p *r = &uu->hfpHandleCallHoldInfoRange.p;
              printf(" p={");
              for(i = 0; i < r->count; ++i)
              {
                struct value_hfpHandleCallHoldInfoRange_p t = get_hfpHandleCallHoldInfoRange_p(r, i);
                putchar('{');
                printf(" lower=%d", t.lower);
                printf(" upper=%d", t.upper);
                putchar('}');
              }
              putchar('}');
            }
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(skip2(skip1(loop3(skip1(skip2(skip1(t, e), e), e), e, &uu->hfpHandleCallHoldInfo.p), e), e), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCallHoldInfo(task, &uu->hfpHandleCallHoldInfo);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCallHoldInfo");
            {
              uint16 i;
              struct region_hfpHandleCallHoldInfo_p *r = &uu->hfpHandleCallHoldInfo.p;
              printf(" p={");
              for(i = 0; i < r->count; ++i)
              {
                struct value_hfpHandleCallHoldInfo_p t = get_hfpHandleCallHoldInfo_p(r, i);
                putchar('{');
                printString("n", &t.n);
                putchar('}');
              }
              putchar('}');
            }
            putchar('\n');
#endif
            continue;
          }
          break;
        case 14:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleIndicatorStatusUpdate.index), e), e), e), e, &uu->hfpHandleIndicatorStatusUpdate.value), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleIndicatorStatusUpdate(task, &uu->hfpHandleIndicatorStatusUpdate);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleIndicatorStatusUpdate");
            printf(" index=%d", uu->hfpHandleIndicatorStatusUpdate.index);
            printf(" value=%d", uu->hfpHandleIndicatorStatusUpdate.value);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 15:
          if(match1(skip1(match1(skip1(loop1(skip1(t, e), e, &uu->hfpHandleIndicatorStatus.d), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleIndicatorStatus(task, &uu->hfpHandleIndicatorStatus);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleIndicatorStatus");
            {
              uint16 i;
              struct region_hfpHandleIndicatorStatus_d *r = &uu->hfpHandleIndicatorStatus.d;
              printf(" d={");
              for(i = 0; i < r->count; ++i)
              {
                struct value_hfpHandleIndicatorStatus_d t = get_hfpHandleIndicatorStatus_d(r, i);
                putchar('{');
                printf(" n=%d", t.n);
                putchar('}');
              }
              putchar('}');
            }
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(t, e), e, &uu->hfpHandleIndicatorList.str), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleIndicatorList(task, &uu->hfpHandleIndicatorList);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleIndicatorList");
            printString("str", &uu->hfpHandleIndicatorList.str);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 16:
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->hfpHandleCallerIdWithName.num), e), e), e), e, &uu->hfpHandleCallerIdWithName.type), e), e), e), e, &uu->hfpHandleCallerIdWithName.saddr), e), e), e), e, &uu->hfpHandleCallerIdWithName.satype), e), e), e), e, &uu->hfpHandleCallerIdWithName.name), e), e), e), e, &uu->hfpHandleCallerIdWithName.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCallerIdWithName(task, &uu->hfpHandleCallerIdWithName);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCallerIdWithName");
            printString("num", &uu->hfpHandleCallerIdWithName.num);
            printf(" type=%d", uu->hfpHandleCallerIdWithName.type);
            printString("saddr", &uu->hfpHandleCallerIdWithName.saddr);
            printString("satype", &uu->hfpHandleCallerIdWithName.satype);
            printString("name", &uu->hfpHandleCallerIdWithName.name);
            printString("ignore", &uu->hfpHandleCallerIdWithName.ignore);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->hfpHandleCallerId.num), e), e), e), e, &uu->hfpHandleCallerId.type), e), e), e), e, &uu->hfpHandleCallerId.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCallerId(task, &uu->hfpHandleCallerId);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCallerId");
            printString("num", &uu->hfpHandleCallerId.num);
            printf(" type=%d", uu->hfpHandleCallerId.type);
            printString("ignore", &uu->hfpHandleCallerId.ignore);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->hfpHandleCallerIdIllegal.num), e), e), e), e, &uu->hfpHandleCallerIdIllegal.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleCallerIdIllegal(task, &uu->hfpHandleCallerIdIllegal);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleCallerIdIllegal");
            printString("num", &uu->hfpHandleCallerIdIllegal.num);
            printString("ignore", &uu->hfpHandleCallerIdIllegal.ignore);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 17:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->hfpHandleSubscriberNumber.alpha), e), e), e), e, &uu->hfpHandleSubscriberNumber.number), e), e), e), e, &uu->hfpHandleSubscriberNumber.type), e), e), e), e, &uu->hfpHandleSubscriberNumber.speed), e), e), e), e, &uu->hfpHandleSubscriberNumber.service), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleSubscriberNumber(task, &uu->hfpHandleSubscriberNumber);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleSubscriberNumber");
            printString("alpha", &uu->hfpHandleSubscriberNumber.alpha);
            printString("number", &uu->hfpHandleSubscriberNumber.number);
            printf(" type=%d", uu->hfpHandleSubscriberNumber.type);
            printString("speed", &uu->hfpHandleSubscriberNumber.speed);
            printf(" service=%d", uu->hfpHandleSubscriberNumber.service);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 18:
          if(match1(skip1(match1(skip1(getString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleNetworkOperatorModeName.mode), e), e), e), e, &uu->hfpHandleNetworkOperatorModeName.format), e), e), e), e, &uu->hfpHandleNetworkOperatorModeName.operator), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleNetworkOperatorModeName(task, &uu->hfpHandleNetworkOperatorModeName);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleNetworkOperatorModeName");
            printf(" mode=%d", uu->hfpHandleNetworkOperatorModeName.mode);
            printf(" format=%d", uu->hfpHandleNetworkOperatorModeName.format);
            printString("operator", &uu->hfpHandleNetworkOperatorModeName.operator);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleNetworkOperatorMode.mode), e), e), e), e, &uu->hfpHandleNetworkOperatorMode.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleNetworkOperatorMode(task, &uu->hfpHandleNetworkOperatorMode);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleNetworkOperatorMode");
            printf(" mode=%d", uu->hfpHandleNetworkOperatorMode.mode);
            printString("ignore", &uu->hfpHandleNetworkOperatorMode.ignore);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 19:
          if(match1(skip1(match1(skip1(getWildString(t, e, &uu->hfpHandleNull.str), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleNull(task, &uu->hfpHandleNull);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleNull");
            printString("str", &uu->hfpHandleNull.str);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 20:
          if(t)
          {
#ifndef TEST_HARNESS
            hfpHandleRing(task);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleRing");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 21:
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpCsrFeaturesHandleBandwidthCodecRes.callername), e), e), e), e, &uu->hfpCsrFeaturesHandleBandwidthCodecRes.rawtext), e), e), e), e, &uu->hfpCsrFeaturesHandleBandwidthCodecRes.sms), e), e), e), e, &uu->hfpCsrFeaturesHandleBandwidthCodecRes.battlevel), e), e), e), e, &uu->hfpCsrFeaturesHandleBandwidthCodecRes.pwrsource), e), e), e), e, &uu->hfpCsrFeaturesHandleBandwidthCodecRes.codecs), e), e), e), e, &uu->hfpCsrFeaturesHandleBandwidthCodecRes.codecbandwidths), e), e), e), e, &uu->hfpCsrFeaturesHandleBandwidthCodecRes.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleBandwidthCodecRes(task, &uu->hfpCsrFeaturesHandleBandwidthCodecRes);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleBandwidthCodecRes");
            printf(" callername=%d", uu->hfpCsrFeaturesHandleBandwidthCodecRes.callername);
            printf(" rawtext=%d", uu->hfpCsrFeaturesHandleBandwidthCodecRes.rawtext);
            printf(" sms=%d", uu->hfpCsrFeaturesHandleBandwidthCodecRes.sms);
            printf(" battlevel=%d", uu->hfpCsrFeaturesHandleBandwidthCodecRes.battlevel);
            printf(" pwrsource=%d", uu->hfpCsrFeaturesHandleBandwidthCodecRes.pwrsource);
            printf(" codecs=%d", uu->hfpCsrFeaturesHandleBandwidthCodecRes.codecs);
            printf(" codecbandwidths=%d", uu->hfpCsrFeaturesHandleBandwidthCodecRes.codecbandwidths);
            printString("ignore", &uu->hfpCsrFeaturesHandleBandwidthCodecRes.ignore);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpCsrFeaturesHandleCodecRes.callername), e), e), e), e, &uu->hfpCsrFeaturesHandleCodecRes.rawtext), e), e), e), e, &uu->hfpCsrFeaturesHandleCodecRes.sms), e), e), e), e, &uu->hfpCsrFeaturesHandleCodecRes.battlevel), e), e), e), e, &uu->hfpCsrFeaturesHandleCodecRes.pwrsource), e), e), e), e, &uu->hfpCsrFeaturesHandleCodecRes.codecs), e), e), e), e, &uu->hfpCsrFeaturesHandleCodecRes.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleCodecRes(task, &uu->hfpCsrFeaturesHandleCodecRes);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleCodecRes");
            printf(" callername=%d", uu->hfpCsrFeaturesHandleCodecRes.callername);
            printf(" rawtext=%d", uu->hfpCsrFeaturesHandleCodecRes.rawtext);
            printf(" sms=%d", uu->hfpCsrFeaturesHandleCodecRes.sms);
            printf(" battlevel=%d", uu->hfpCsrFeaturesHandleCodecRes.battlevel);
            printf(" pwrsource=%d", uu->hfpCsrFeaturesHandleCodecRes.pwrsource);
            printf(" codecs=%d", uu->hfpCsrFeaturesHandleCodecRes.codecs);
            printString("ignore", &uu->hfpCsrFeaturesHandleCodecRes.ignore);
            putchar('\n');
#endif
            continue;
          }
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpCsrFeaturesHandleNormalRes.callername), e), e), e), e, &uu->hfpCsrFeaturesHandleNormalRes.rawtext), e), e), e), e, &uu->hfpCsrFeaturesHandleNormalRes.sms), e), e), e), e, &uu->hfpCsrFeaturesHandleNormalRes.battlevel), e), e), e), e, &uu->hfpCsrFeaturesHandleNormalRes.pwrsource), e), e), e), e, &uu->hfpCsrFeaturesHandleNormalRes.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleNormalRes(task, &uu->hfpCsrFeaturesHandleNormalRes);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleNormalRes");
            printf(" callername=%d", uu->hfpCsrFeaturesHandleNormalRes.callername);
            printf(" rawtext=%d", uu->hfpCsrFeaturesHandleNormalRes.rawtext);
            printf(" sms=%d", uu->hfpCsrFeaturesHandleNormalRes.sms);
            printf(" battlevel=%d", uu->hfpCsrFeaturesHandleNormalRes.battlevel);
            printf(" pwrsource=%d", uu->hfpCsrFeaturesHandleNormalRes.pwrsource);
            printString("ignore", &uu->hfpCsrFeaturesHandleNormalRes.ignore);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 22:
          if(t)
          {
#ifndef TEST_HARNESS
            hfpHandleError(task);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleError");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 23:
          if(match1(skip1(match1(skip1(getWildString(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(getString(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpCsrFeaturesHandleSmsInd.smsIndex), e), e), e), e, &uu->hfpCsrFeaturesHandleSmsInd.senderNum), e), e), e), e, &uu->hfpCsrFeaturesHandleSmsInd.senderName), e), e), e), e, &uu->hfpCsrFeaturesHandleSmsInd.ignore), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleSmsInd(task, &uu->hfpCsrFeaturesHandleSmsInd);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleSmsInd");
            printf(" smsIndex=%d", uu->hfpCsrFeaturesHandleSmsInd.smsIndex);
            printString("senderNum", &uu->hfpCsrFeaturesHandleSmsInd.senderNum);
            printString("senderName", &uu->hfpCsrFeaturesHandleSmsInd.senderName);
            printString("ignore", &uu->hfpCsrFeaturesHandleSmsInd.ignore);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 24:
          if(match1(skip1(match1(skip1(getString(skip1(t, e), e, &uu->hfpCsrFeaturesHandleTextInd.text), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleTextInd(task, &uu->hfpCsrFeaturesHandleTextInd);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleTextInd");
            printString("text", &uu->hfpCsrFeaturesHandleTextInd.text);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 25:
          if(match1(skip1(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->hfpHandleExtendedError.err), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpHandleExtendedError(task, &uu->hfpHandleExtendedError);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleExtendedError");
            printf(" err=%d", uu->hfpHandleExtendedError.err);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 26:
          if(t)
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleBatteryLevelRequestInd(task);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleBatteryLevelRequestInd");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 27:
          if(match1(skip1(match1(skip1(getString(skip1(t, e), e, &uu->hfpCsrFeaturesHandleGetSmsRes.sms), e), e), e), e))
          {
#ifndef TEST_HARNESS
            hfpCsrFeaturesHandleGetSmsRes(task, &uu->hfpCsrFeaturesHandleGetSmsRes);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpCsrFeaturesHandleGetSmsRes");
            printString("sms", &uu->hfpCsrFeaturesHandleGetSmsRes.sms);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 28:
          if(t)
          {
#ifndef TEST_HARNESS
            hfpHandleNoCarrierInd(task);
#endif
#ifdef TEST_HARNESS
            printf("Called hfpHandleNoCarrierInd");
            putchar('\n');
#endif
            continue;
          }
          break;
        default:
          break;
      }
      /*
        The message does not contain a recognised AT command or response.
        Pass the data on to the application to have a go at 
      */
unrecognised:
#ifndef TEST_HARNESS
      handleUnrecognised(s, (uint16) (p-s), task);
#endif
#ifdef TEST_HARNESS
      printf("Called handleUnrecognised\n");
#endif
    }
  }

  return s;
}

/*
hfpHandleOk : 
OK


hfpHandleError : 
ERROR


hfpHandleRing : 
RING


hfpHandleInBandRingToneDisable : 
+BSIR: 0


hfpHandleInBandRingToneEnable : 
+BSIR: 1


hfpHandleCallHoldInfoCommon : 
+CHLD: (0,1,1x,2,2x,3,4)


hfpHandleNull
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   MatchChar M
   MatchChar B
   MatchChar A
   MatchChar N
   Match "=:"
   GetWildString str
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleOk
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar O
   MatchChar K
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleError
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar E
   MatchChar R
   MatchChar R
   MatchChar O
   MatchChar R
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleExtendedError
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar M
   MatchChar E
   Skip " \t"
   MatchChar E
   MatchChar R
   MatchChar R
   MatchChar O
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber err
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleRing
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar R
   MatchChar I
   MatchChar N
   MatchChar G
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleNoCarrierInd
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar N
   MatchChar O
   Skip " \t"
   MatchChar C
   MatchChar A
   MatchChar R
   MatchChar R
   MatchChar I
   MatchChar E
   MatchChar R
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleSupportedFeaturesInd
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar R
   MatchChar S
   MatchChar F
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber supportedfeat
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleIndicatorStatus
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar I
   MatchChar N
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   (Loop d 2 99   GetNumber n
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
)
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleIndicatorList
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar I
   MatchChar N
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetWildString str
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCallHoldInfoRange
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar H
   MatchChar L
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   Skip "()"
   Skip " \t"
   (Loop p 1 99   GetNumber lower
   Skip " \t"
   Skip "-"
   Skip " \t"
   GetNumber upper
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
)
   Skip " \t"
   Skip "()"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCallHoldInfo
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar H
   MatchChar L
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   Skip "()"
   Skip " \t"
   (Loop p 1 99   GetString n
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
)
   Skip " \t"
   Skip "()"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleIndicatorStatusUpdate
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar I
   MatchChar E
   MatchChar V
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber index
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber value
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleInBandRingTone
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar S
   MatchChar I
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber enable
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleVoiceRecognitionStatus
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar V
   MatchChar R
   MatchChar A
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber enable
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleSpeakerGain
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar V
   MatchChar G
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber gain
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleMicrophoneGain
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar V
   MatchChar G
   MatchChar M
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber gain
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCallerIdWithName
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar I
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString num
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber type
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString saddr
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString satype
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString name
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCallerId
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar I
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString num
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber type
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCallerIdIllegal
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar I
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString num
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleDataResponse
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar I
   MatchChar N
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString num
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleDataResponseExtended
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar I
   MatchChar N
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString num
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCallWaitingNotificationWithName
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar C
   MatchChar W
   MatchChar A
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString num
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber type
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber class
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString name
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCallWaitingNotification
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar C
   MatchChar W
   MatchChar A
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString num
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber type
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCallWaitingNotificationIllegal
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar C
   MatchChar W
   MatchChar A
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString num
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleSubscriberNumber
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar N
   MatchChar U
   MatchChar M
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString alpha
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString number
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber type
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString speed
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber service
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleResponseHold
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar T
   MatchChar R
   MatchChar H
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber state
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCurrentCallsWithNumber
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar C
   MatchChar C
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber idx
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber dir
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber status
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber mprty
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString number
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber type
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCurrentCalls
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar C
   MatchChar C
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber idx
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber dir
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber status
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber mprty
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCurrentCallsWithNumber
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar C
   MatchChar C
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber idx
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber dir
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber status
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber mprty
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString number
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber type
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleCurrentCalls
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar L
   MatchChar C
   MatchChar C
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber idx
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber dir
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber status
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber mprty
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleNetworkOperatorModeName
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar O
   MatchChar P
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber format
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString operator
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleNetworkOperatorMode
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar O
   MatchChar P
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleBandwidthCodecRes
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar S
   MatchChar F
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber callername
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber rawtext
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber sms
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber battlevel
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber pwrsource
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber codecs
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber codecbandwidths
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleCodecRes
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar S
   MatchChar F
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber callername
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber rawtext
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber sms
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber battlevel
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber pwrsource
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber codecs
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleNormalRes
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar S
   MatchChar F
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber callername
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber rawtext
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber sms
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber battlevel
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber pwrsource
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleTextInd
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar T
   MatchChar X
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString text
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleSmsInd
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar S
   MatchChar M
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber smsIndex
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString senderNum
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetString senderName
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString ignore
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleGetSmsRes
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar G
   MatchChar E
   MatchChar T
   MatchChar S
   MatchChar M
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString sms
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleModifyIndicatorsInd
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   (Loop p 1 99   Skip " \t"
   Skip "()"
   Skip " \t"
   GetNumber ind
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber val
   Skip " \t"
   Skip "()"
   Skip " \t"
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
)
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleDisableIndicatorsInd
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   MatchChar 0
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpCsrFeaturesHandleBatteryLevelRequestInd
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar S
   MatchChar R
   MatchChar B
   MatchChar A
   MatchChar T
   MatchChar T
   Skip "?"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


hfpHandleResponseWbsCodec
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar C
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber codec
   Skip " \t"
   Match "\r\n"
   Skip " \t"
   Match "\r\n"


*/
