#ifndef USB_DEVICE_CLASS_REMOVE_CHARGING

#ifndef _USB_DEVICE_BATTERY_CHARGING_H
#define _USB_DEVICE_BATTERY_CHARGING_H


bool usbEnumerateBatteryCharging(Task app_task);


#endif /* _USB_DEVICE_BATTERY_CHARGING_H */

#endif /* !USB_DEVICE_CLASS_REMOVE_CHARGING */

